### ISSUE TITLE
Unable to refresh token if no scope is defined

### ISSUE THREAD

**Issue by faxioman** [hiidef/oauth2app#9]
Trying to refresh a token without scope defined always throw an exception.
The method _validate_refresh_token in oauth2app / token should initialize self.scope to [] if no scope is used.

Thanks

**Comment by bhagany** [comment]
Confused about this one - what exception is being thrown in this case?

**Comment by faxioman** [comment]
Django try to execute this code in _get_refresh_token:

access_ranges = list(AccessRange.objects.filter(key__in=self.scope))

If self.scope is None, Django throw an exception

**Comment by faxioman** [comment]
I think that an "else self.scope = []" at end of _validate_refresh_token method should be resolutive.

**Comment by bhagany** [comment]
Looks like we had this problem in several places - I decided to check for self.scope being populated in _get_refresh_token, and the other methods like it.  I believe that should solve the problem.  Commit coming up.
